"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, Download, Loader2, Sparkles, Check, Cloud, Copy, Pencil } from "lucide-react";
import { saveCoverLetter, getCoverLetter } from "@/lib/actions/cover-letters";
import { getResume } from "@/lib/actions/resumes";
import { downloadCoverLetterPDF } from "@/components/cover-letter-pdf";
import { ResumeData } from "@/types/resume";
import { LimitModal } from "@/components/limit-modal";
import { UpgradePlanModal } from "@/components/upgrade-plan-modal";

export default function CoverLetterBuilderPage() {
    const searchParams = useSearchParams();
    const router = useRouter();

    const resumeId = searchParams.get("resume");
    const existingId = searchParams.get("id");

    const [coverLetterId] = useState(() => existingId || crypto.randomUUID());
    const [name, setName] = useState("Cover Letter");
    const [content, setContent] = useState("");
    const [displayedContent, setDisplayedContent] = useState("");
    const [jobDescription, setJobDescription] = useState("");
    const [targetJob, setTargetJob] = useState("");
    const [targetCompany, setTargetCompany] = useState("");
    const [resumeData, setResumeData] = useState<ResumeData | null>(null);
    const [isLimitModalOpen, setIsLimitModalOpen] = useState(false);
    const [limitFeature, setLimitFeature] = useState("");
    const [isUpgradeModalOpen, setIsUpgradeModalOpen] = useState(false);

    const [isLoading, setIsLoading] = useState(true);
    const [isGenerating, setIsGenerating] = useState(false);
    const [isTyping, setIsTyping] = useState(false);
    const [isSaving, setIsSaving] = useState(false);
    const [isSaved, setIsSaved] = useState(false);
    const [copied, setCopied] = useState(false);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

    const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);
    const typewriterRef = useRef<NodeJS.Timeout | null>(null);

    // Typewriter effect function
    const typewriterEffect = useCallback((fullText: string) => {
        setIsTyping(true);
        setDisplayedContent("");
        let currentIndex = 0;
        const speed = 15; // ms per character

        const type = () => {
            if (currentIndex < fullText.length) {
                // Type 3-5 characters at a time for faster effect
                const charsToAdd = Math.min(3 + Math.floor(Math.random() * 3), fullText.length - currentIndex);
                setDisplayedContent(fullText.slice(0, currentIndex + charsToAdd));
                currentIndex += charsToAdd;
                typewriterRef.current = setTimeout(type, speed);
            } else {
                setIsTyping(false);
                setContent(fullText);
            }
        };

        type();
    }, []);

    // Load existing cover letter or resume data
    useEffect(() => {
        const loadData = async () => {
            setIsLoading(true);

            try {
                // If editing existing cover letter
                if (existingId) {
                    const coverLetter = await getCoverLetter(existingId);
                    if (coverLetter) {
                        setName(coverLetter.name);
                        setContent(coverLetter.content);
                        setDisplayedContent(coverLetter.content);
                        setJobDescription(coverLetter.job_description || "");
                        setTargetJob(coverLetter.target_job || "");
                        setTargetCompany(coverLetter.target_company || "");

                        // Load associated resume if exists
                        if (coverLetter.resume_id) {
                            const resume = await getResume(coverLetter.resume_id);
                            if (resume?.data) {
                                setResumeData(resume.data as ResumeData);
                            }
                        }
                    }
                }
                // If creating from resume - auto-generate if tailored
                else if (resumeId) {
                    const resume = await getResume(resumeId);
                    if (resume) {
                        const data = resume.data as ResumeData;
                        setResumeData(data);
                        const job = resume.target_job || data.targetJob || data.name || "";
                        const company = resume.target_company || data.targetCompany || "";
                        setTargetJob(job);
                        setTargetCompany(company);
                        setName(`Cover Letter for ${company || job || "Position"}`);

                        // Load job description from resume if it was tailored
                        if (resume.job_description) {
                            setJobDescription(resume.job_description);
                            // Mark for auto-generation after loading completes
                            setHasAutoGenerated(false);
                        }
                    }
                }
            } catch (error) {
                console.error("Error loading data:", error);
            } finally {
                setIsLoading(false);
            }
        };

        loadData();
    }, [existingId, resumeId]);

    // Auto-generate when loading a tailored resume (only for new cover letters)
    useEffect(() => {
        if (
            !isLoading &&
            !existingId &&
            resumeData &&
            jobDescription &&
            !hasAutoGenerated &&
            !content
        ) {
            setHasAutoGenerated(true);
            generateCoverLetterWithTypewriter();
        }
    }, [isLoading, existingId, resumeData, jobDescription, hasAutoGenerated, content]);

    // Auto-save with debounce
    const saveToDb = useCallback(async () => {
        if (!content.trim()) return;

        setIsSaving(true);
        try {
            const result = await saveCoverLetter(
                coverLetterId,
                name,
                content,
                resumeId || undefined,
                targetJob,
                targetCompany,
                jobDescription
            );

            if (result.success) {
                setIsSaved(true);
                setTimeout(() => setIsSaved(false), 2000);
            } else {
                console.error("Error saving:", result.error);
                if (result.error?.includes("limit")) {
                    setLimitFeature("Active Cover Letters");
                    setIsLimitModalOpen(true);
                }
            }
        } catch (error) {
            console.error("Error saving:", error);
        } finally {
            setIsSaving(false);
        }
    }, [coverLetterId, name, content, resumeId, targetJob, targetCompany, jobDescription]);

    // Debounced auto-save
    useEffect(() => {
        if (content.trim() && !isTyping) {
            if (saveTimeoutRef.current) {
                clearTimeout(saveTimeoutRef.current);
            }
            saveTimeoutRef.current = setTimeout(saveToDb, 2000);
        }

        return () => {
            if (saveTimeoutRef.current) {
                clearTimeout(saveTimeoutRef.current);
            }
        };
    }, [content, saveToDb, isTyping]);

    // Cleanup typewriter on unmount
    useEffect(() => {
        return () => {
            if (typewriterRef.current) {
                clearTimeout(typewriterRef.current);
            }
        };
    }, []);

    // Generate cover letter with typewriter effect
    const generateCoverLetterWithTypewriter = async () => {
        if (!resumeData) {
            alert("Please select a resume first");
            return;
        }

        if (!jobDescription.trim()) {
            alert("Please paste the job description first");
            return;
        }

        setIsGenerating(true);
        setDisplayedContent("");
        try {
            const response = await fetch("/api/resume/ai", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    action: "generate-cover-letter",
                    data: {
                        resumeData,
                        jobTitle: targetJob,
                        companyName: targetCompany,
                        jobDescription
                    }
                })
            });

            const result = await response.json();
            if (result.success && result.data) {
                setIsGenerating(false);
                typewriterEffect(result.data);
            } else {
                setIsGenerating(false);
                alert("Failed to generate cover letter. Please try again.");
            }
        } catch (error) {
            console.error("Error generating:", error);
            setIsGenerating(false);
            alert("Failed to generate cover letter. Please try again.");
        }
    };

    // Copy to clipboard
    const copyToClipboard = async () => {
        try {
            await navigator.clipboard.writeText(content || displayedContent);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (error) {
            console.error("Failed to copy:", error);
        }
    };

    // Download as PDF
    const downloadAsPDF = async () => {
        const textContent = content || displayedContent;
        if (!textContent) return;

        try {
            // Check & Track Usage Limit
            const { trackUsageAction } = await import("@/lib/actions/usage");
            const result = await trackUsageAction("download_cover_letter");

            if (!result.success) {
                if (result.error?.includes("limit reached")) {
                    setLimitFeature("Cover Letter Downloads");
                    setIsLimitModalOpen(true);
                } else {
                    alert(result.error || "Usage limit reached.");
                }
                return;
            }

            await downloadCoverLetterPDF(textContent, name);
        } catch (error) {
            console.error("Failed to download PDF:", error);
            alert("Failed to generate PDF. Please try again.");
        }
    };

    // Switch to edit mode
    const enableEditMode = () => {
        if (isTyping && typewriterRef.current) {
            clearTimeout(typewriterRef.current);
        }
        setContent(displayedContent);
        setIsTyping(false);
    };

    if (isLoading) {
        return (
            <div className="flex flex-1 items-center justify-center">
                <Loader2 className="w-8 h-8 animate-spin text-primary" />
            </div>
        );
    }

    return (
        <div className="flex flex-1 flex-col h-full">
            {/* Header */}
            <div className="flex items-center justify-between p-4 border-b bg-background">
                <div className="flex items-center gap-4">
                    <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => router.push("/dashboard/cover-letters")}
                    >
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back
                    </Button>
                    <div className="h-6 w-px bg-border" />
                    <input
                        type="text"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        className="text-lg font-semibold bg-transparent border-none outline-none focus:ring-0"
                    />
                    {targetCompany && (
                        <span className="text-sm text-muted-foreground">
                            — Targeting: {targetCompany}
                        </span>
                    )}
                </div>
                <div className="flex items-center gap-3">
                    {/* Save indicator */}
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                        {isSaving ? (
                            <>
                                <Loader2 className="w-3 h-3 animate-spin" />
                                <span>Saving...</span>
                            </>
                        ) : isSaved ? (
                            <>
                                <Check className="w-3 h-3 text-green-500" />
                                <span className="text-green-500">Saved</span>
                            </>
                        ) : (
                            <>
                                <Cloud className="w-3 h-3" />
                                <span>Auto-save</span>
                            </>
                        )}
                    </div>

                    <Button
                        variant="outline"
                        size="sm"
                        onClick={copyToClipboard}
                        disabled={!content && !displayedContent}
                    >
                        {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                        {copied ? "Copied!" : "Copy"}
                    </Button>

                    <Button
                        size="sm"
                        onClick={downloadAsPDF}
                        disabled={!content && !displayedContent}
                    >
                        <Download className="w-4 h-4 mr-2" />
                        Download PDF
                    </Button>
                </div>
            </div>

            {/* Main content */}
            <div className="flex flex-1 overflow-hidden">
                {/* Left panel - Job Description */}
                <div className="w-1/3 border-r p-4 overflow-y-auto bg-muted/30">
                    <div className="space-y-4">
                        <div>
                            <h3 className="font-semibold mb-2">Selected Resume</h3>
                            {resumeData ? (
                                <div className="p-3 rounded-lg bg-primary/10 border border-primary/20">
                                    <p className="font-medium">{resumeData.personalInfo.fullName}</p>
                                    <p className="text-sm text-muted-foreground">{resumeData.name}</p>
                                </div>
                            ) : (
                                <div className="p-3 rounded-lg bg-muted text-center">
                                    <p className="text-sm text-muted-foreground">No resume selected</p>
                                    <Button
                                        variant="link"
                                        size="sm"
                                        onClick={() => router.push("/dashboard/cover-letters")}
                                    >
                                        Select a resume
                                    </Button>
                                </div>
                            )}
                        </div>

                        <div>
                            <label className="text-sm font-medium">Target Company</label>
                            <input
                                type="text"
                                value={targetCompany}
                                onChange={(e) => setTargetCompany(e.target.value)}
                                placeholder="e.g., Google, Meta, Startup Inc."
                                className="w-full mt-1 px-3 py-2 rounded-md border bg-background text-sm"
                            />
                        </div>

                        <div>
                            <label className="text-sm font-medium">Target Position</label>
                            <input
                                type="text"
                                value={targetJob}
                                onChange={(e) => setTargetJob(e.target.value)}
                                placeholder="e.g., Senior Software Engineer"
                                className="w-full mt-1 px-3 py-2 rounded-md border bg-background text-sm"
                            />
                        </div>

                        <div>
                            <label className="text-sm font-medium">Job Description</label>
                            <p className="text-xs text-muted-foreground mb-2">
                                Paste the full job description to generate a tailored cover letter
                            </p>
                            <Textarea
                                value={jobDescription}
                                onChange={(e) => setJobDescription(e.target.value)}
                                placeholder="Paste the job description here..."
                                className="h-[200px] max-h-[200px] text-sm resize-none overflow-y-auto"
                            />
                        </div>

                        <Button
                            className="w-full"
                            onClick={generateCoverLetterWithTypewriter}
                            disabled={isGenerating || isTyping || !resumeData || !jobDescription.trim()}
                        >
                            {isGenerating ? (
                                <>
                                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                    Generating...
                                </>
                            ) : isTyping ? (
                                <>
                                    <Pencil className="w-4 h-4 mr-2 animate-pulse" />
                                    Writing...
                                </>
                            ) : (
                                <>
                                    <Sparkles className="w-4 h-4 mr-2" />
                                    {content ? "Regenerate" : "Generate Cover Letter"}
                                </>
                            )}
                        </Button>
                    </div>
                </div>

                {/* Right panel - Cover Letter Preview/Editor */}
                <div className="flex-1 p-6 overflow-y-auto">
                    <div className="max-w-2xl mx-auto">
                        <div className="bg-white dark:bg-gray-900 rounded-lg border shadow-sm p-8 min-h-[600px]">
                            {isGenerating ? (
                                <div className="flex flex-col items-center justify-center h-[500px] text-center text-muted-foreground">
                                    <Loader2 className="w-12 h-12 mb-4 animate-spin text-primary" />
                                    <h3 className="text-lg font-medium mb-2">Generating your cover letter...</h3>
                                    <p className="max-w-sm text-sm">
                                        Analyzing your resume and the job description to create a personalized cover letter.
                                    </p>
                                </div>
                            ) : isTyping ? (
                                <div className="relative">
                                    <div
                                        className="w-full min-h-[500px] text-base leading-relaxed whitespace-pre-wrap"
                                        style={{ fontFamily: "Georgia, serif" }}
                                    >
                                        {displayedContent}
                                        <span className="inline-block w-0.5 h-5 bg-primary ml-0.5 animate-pulse" />
                                    </div>
                                    <Button
                                        variant="outline"
                                        size="sm"
                                        className="absolute top-0 right-0"
                                        onClick={enableEditMode}
                                    >
                                        <Pencil className="w-3 h-3 mr-1" />
                                        Edit
                                    </Button>
                                </div>
                            ) : content || displayedContent ? (
                                <Textarea
                                    value={content || displayedContent}
                                    onChange={(e) => setContent(e.target.value)}
                                    className="w-full min-h-[500px] border-none resize-none focus:ring-0 text-base leading-relaxed"
                                    style={{ fontFamily: "Georgia, serif" }}
                                    placeholder="Your cover letter will appear here..."
                                />
                            ) : (
                                <div className="flex flex-col items-center justify-center h-[500px] text-center text-muted-foreground">
                                    <Sparkles className="w-12 h-12 mb-4 opacity-50" />
                                    <h3 className="text-lg font-medium mb-2">Ready to Generate</h3>
                                    <p className="max-w-sm">
                                        {resumeData
                                            ? jobDescription
                                                ? "Click 'Generate Cover Letter' to create a tailored letter."
                                                : "Paste the job description and click 'Generate Cover Letter' to create a tailored letter."
                                            : "Select a resume from the Cover Letters page to get started."
                                        }
                                    </p>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            {/* Modals */}
            <LimitModal
                open={isLimitModalOpen}
                onOpenChange={setIsLimitModalOpen}
                feature={limitFeature}
                onUpgrade={() => {
                    setIsLimitModalOpen(false);
                    setIsUpgradeModalOpen(true);
                }}
            />
            <UpgradePlanModal
                open={isUpgradeModalOpen}
                onClose={() => setIsUpgradeModalOpen(false)}
                currentPlan="Free"
            />
        </div >
    );
}
